real_state_sales:
  outputs:
    dev:
      dataset: retail_project_dataset
      fixed_retries: 1
      keyfile: ~/.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: zoomcamp-2024-psergios
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev